import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import localFont from "next/font/local";
import { Toaster } from "@/components/ui/sonner";

import { CartStoreProvider } from "@/store/cart-store-provider";
import "./globals.css";

const interFont = localFont({
  src: "../fonts/Inter-VariableFont_slnt,wght.ttf",
  display: "swap",
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          interFont.className
        )}
      >
        <CartStoreProvider>{children}</CartStoreProvider>
        <Toaster position="bottom-center" richColors />
      </body>
    </html>
  );
}
